#image: registry.gitlab.com/lianqiw/maos
image: gcc
build:
  stage: build

  tags:
    - saas-linux-medium-amd64
  before_script: 
    # install the necessary library to avoid pulling github LFS
    - whoami
    - free -m | grep -v "Swap" # RAM
    - df -h| grep -E "Filesystem|overlay" # storage
    - lscpu | grep -E "^CPU\(s\)" # CPUs
    - apt-get update
    - apt-get install -y libfftw3-dev libsuitesparse-dev libcmocka-dev libopenblas-openmp-dev libwebsockets-dev
  script: 
    - ./autogen.sh 
    - mkdir -p build && cd build && ../configure && make check #&& make check #gitlab fails maos job out of no reason
  artifacts:
    when: on_failure
    paths:
      - build/config.*
      - build/*/*.log
    exclude: 
      - build/*/.libs
      - build/*/*.o
      - build/*/*.bin
      - build/*/*.fits
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    #paths:
    #  - ~/.aos  
