image: registry.gitlab.com/lianqiw/maos

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script: 
    #- apt update && apt -y install make autoconf 
    #- apt -y install gfortran || update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 1
    #- apt -y install libfftw3-dev libblas-dev liblapack-dev #libcholmod3 libwebsockets-dev
  script: 
    # The default is to run as root, which crashes immediately.  
    # The image already has user lianqiw
    - su lianqiw -c "whoami && ./autogen.sh && mkdir -p build && cd build && ../configure --enable-release && bin/maos aper.d=5 sim.end=10"
  artifacts:
    when: always
    paths:
      - build/config.log
      - build/external/compile.log
      - build/bin/
  cache:
    paths:
      - ~lianqiw/.aos
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - cd build/bin
#    - ../../scripts/maos_check.sh 5 > maos_check.txt
#  artifacts:
#    paths:
#      - build/bin/maos_check*
#      
    
