name: CI in Linux
#Also updates documentation with branch gh-pages
on:
  push:
    branches-ignore:
    - gh-pages
  pull_request:
    branches-ignore:
    - gh-pages
  
jobs:
  build:
    if: github.repository == 'lianqiw/maos'
    runs-on: ubuntu-latest

    steps:
    - name: setup environment #install all external libraryes to avoid distcheck failure
      run: sudo apt-get install -y libfftw3-dev libsuitesparse-dev libcmocka-dev libopenblas-openmp-dev graphviz doxygen texlive-latex-base
      continue-on-error: true
    - name: checkout
      uses: actions/checkout@v4
      with:
        path: maos
    - name: autogen
      run: |
        cd maos && ./autogen.sh
    - name: configure and make
      run: |
        mkdir build && cd build
        ../maos/configure --enable-release --enable-doxygen --prefix=$(pwd)/../external
        make -j8
        make check
    - name: make doc
      run: cd build && make doc
    - name: checkout gh-pages 
      if: github.ref == 'refs/heads/master'
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: doc
    - name: update doc and commit
      if: github.ref == 'refs/heads/master'
      run: | 
        cd doc
        rm -rf *
        cp -a ../build/doxygen-doc/html/* .
        git config user.name Lianqi Wang
        git config user.email lianqiw@gmail.com
        git add .
        git commit -m "Automatically updated" && git push || echo "no need to update doc"
    - name: clang make
      run: |
        mkdir clang && cd clang
        ../maos/configure --enable-release --prefix=$(pwd)/../external CC=clang
        make -j8
        make check
    - name: maos result check
      run: cd build/bin && ../../maos/scripts/maos_check.sh 5
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: maos-linux
        retention-days: 30
        path: |
          */config.*
          build/test/*.log
          build/bin/maos_check_*.*
