name: CI in macos

on:
  push:
    branches-ignore:
    - gh-pages
  pull_request:
    branches-ignore:
    - gh-pages

jobs:
  build:
    if: github.repository == 'lianqiw/maos'
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        path: maos
    - name: autogen
      run: |
        cd maos && ./autogen.sh
    - name: configure and make
      run: |
        mkdir build && cd build
        ../maos/configure --enable-release --disable-binary --prefix=$(pwd)/../external
        make -j8
    - name: make check
      run: cd build && make check
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: maos-macos
        retention-days: 30
        path: |
          build/config.h
          build/config.log
          build/test/*.log
          build/test/maos_check_*.*
          #build/bin/
          #build/test/
          #!build/test/*.bin
          #!build/test/*.fits
          #!build/test/*.o
          #!build/test/*.trs
          #!build/*/Makefile

